# Generated by Django 3.0.7 on 2020-06-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_miziziuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidprocedure',
            name='image',
            field=models.ImageField(default='https://homepages.cae.wisc.edu/~ece533/images/airplane.png', upload_to='media/'),
        ),
    ]
